### ISSUE TITLE
CityScope view and Editor views are the same after login 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#45]
in https://github.com/CityScope/CSL_Hamburg_Grasbrook/commit/a82b5849b53434df02ded3bbb4c39ca9e1bd39d2, when user logs in => then goes back to the main menu screen => then goes to the map view => the map is editable 

Should be: map view => only shows tangible table state with no edit functionality 
editor view => editable for logged in user

**Comment by illsio** [comment]
the user stays logged in until he/she is actively logging out. i would suggest that this is the expected behavior. normally websites do not log out by url change.
user logs in => back to the main menu screen => clicks log out => goes to the map view => map is NOT editable
i now understand what you mean, but what is the reason for your suggested behaviour? fequent switches from editors to non editors on one input device?

**Comment by RELNO** [comment]
You're right that there might be less switches between map and editor views, but still if they occur, this might confuse the use (two clickable options that are the same).

My suggestion is to implement a simple 'X' button on the editor view that: prompts for save; logs out the user; brings them back to main menu. 

downside here is that users are logged off when they click it. But I'm not sure it's a bad idea from security standpoint.

**Comment by illsio** [comment]
done?

**Comment by RELNO** [comment]
The 'x' works well, thanks. I'm still confused as to the observatory mode when still logged in.

**Comment by illsio** [comment]
When a user is logged in, there is no observatory mode.
If a logged in user is looking at the map - editing mode is always active.

**Comment by RELNO** [comment]
Understood, I find it a bit confusing. Let's leave it as is for now and discuss it next week
