### ISSUE TITLE
No indication of modules loading 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook#82]
there is no loading bar/icon when requests are made, which makes it hard for users to assume cause and effect of edits.

**Comment by andredaa** [comment]
https://trello.com/c/9dS98MIA/8-indicate-simulation-is-running-in-the-background

**Comment by illsio** [comment]
oh sorry - missed out on linking this ticket to
https://github.com/CityScope/CSL_Hamburg_Grasbrook/commit/906a942e5e96644261953174c03477c4057acdea

**Comment by RELNO** [comment]
@illsio thanks, I can see it with Noise, might be good to do the same for the grid layer that takes ~10-20 on init to load. 
As for other layers (abm, access) we'll need to figure out a more refined loading UI, as each has sublayers. Let's keep it to another issue as we move to integrate these modules.

**Comment by luftj** [comment]
done for simulation map layers as well as charts ( 50aa256). Closing.

**Comment by RELNO** [comment]
not working on 2nd attempt to append changes to grid and save.

**Comment by luftj** [comment]
![grafik](https://user-images.githubusercontent.com/20200776/70331292-78634780-183f-11ea-8ead-6bd55862f49d.png)
works for me.
It might take a few moments to show, since it only starts showing as soon as the front-end gets a cityIO update. Otherwise we don't know the grid's hash and can't cross-check. Since we are only able to poll from cityIO on regular intervals it might take up to the currently set 10 second update interval to show. This interval is subject to change.

**Comment by RELNO** [comment]
works now, thanks. What I saw is that walkability layer updates forever (I've stopped after 5min). Not sure if the module is off or not. Closing
